# Generated by Django 3.1 on 2020-08-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='logged_status',
            field=models.CharField(choices=[('S', 'Logged In'), ('F', 'Logged Out')], default='F', max_length=1),
            preserve_default=False,
        ),
    ]
